export enum GridFilterType {
    CONTAIN  = 'CONTAIN',
    GREATER_THAN = 'GREATER_THAN',
    LESS_THAN = 'LESS_THAN',
    GREATER_THAN_OR_EQUAL = 'GREATER_THAN_OR_EQUAL',
    LESS_THAN_OR_EQUAL = 'LESS_THAN_OR_EQUAL',
    EQUAL = 'EQUAL',
    NOT_EQUAL = 'NOT_EQUAL',
    NOT_CONTAIN = 'NOT_CONTAIN',
}
